### ISSUE TITLE
GTM code not firing. Getting error. 

### ISSUE THREAD

**Issue by ranjeetranjan** [magepal/magento2-google-tag-manager#56]
```
nable to resolve the source file for 'frontend/Mgs/claue/en_US/magepalGtmDatalayer.js' #0 /var/www/shahnaz.adsizzlergroup.com/public_html/vendor/magento/framework/App/StaticResource.php(121): Magento\Framework\View\Asset\File->getSourceFile() #1 /var/www/shahnaz.adsizzlergroup.com/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\StaticResource->launch() #2 /var/www/shahnaz.adsizzlergroup.com/public_html/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource)) #3 {main}
Request URL: 
http://shahnaz.adsizzlergroup.com/pub/static/frontend/Mgs/claue/en_US/magepalGtmDatalayer.js
Request Method: 
GET
Status Code: 
404 Not Found (from disk cache)
Remote Address: 
104.31.89.173:80
Referrer Policy: 
no-referrer-when-downgrade
```

**Comment by ranjeetranjan** [comment]
@srenon We simply install your GTM command line but why it's not creating I am not able to figure out. Do you have any suggestion? All other extension working perfectly.
